### ISSUE TITLE
Registry API Docs

### ISSUE THREAD

**Issue by wesleytodd** [Netflix/spectator-js#29]
Are any api docs for the a registry instance? Preferably there would be a section in the `README.md` which covers examples of all the available metric types and the signature of the methods which create and report them.  I would be happy to contribute on them if someone with more context could start it off in the right direction.

**Comment by brharrington** [comment]
Documentation is a bit thin right now. There is a work in-progress to create a unified documentation page for Atlas and the Spectator clients for various languages:

https://github.com/Netflix/atlas-docs

There is still quite a bit of work to do, but we hope to have it in pretty good shape by the end of the quarter. Contributions are welcome, but it would probably be good to sync up a bit to avoid duplication of efforts.

**Comment by wesleytodd** [comment]
Thanks @brharrington, sounds like I should wait until the end of the quarter to to avoid duplicate work.  I will continue to read the code to figure how how to do thing, thanks for the update!
